all: MadLib.class Cashier.class GreatCircle.class RGBtoCMYK.class

MadLib.class: MadLib.java
	javac MadLib.java

Cashier.class: Cashier.java
	javac Cashier.java

GreatCircle.class: GreatCircle.java
	javac GreatCircle.java

RGBtoCMYK.class: RGBtoCMYK.java
	javac RGBtoCMYK.java
