all: MadLib.class Cashier.class GreatCircle.class ColorConvension.class

MadLib.class: MadLib.java
	javac MadLib.java

Cashier.class: Cashier.java
	javac Cashier.java

GreatCircle.class: GreatCircle.java
	javac GreatCircle.java

ColorConvension.class: ColorConvension.java
	javac ColorConvension.java
