all: AsciiArt.class RandomWalker.class RandomWalkers.class SpecDay.class

AsciiArt.class: AsciiArt.java
	javac AsciiArt.java

RandomWalker.class: RandomWalker.java
	javac RandomWalker.java

RandomWalkers.class: RandomWalkers.java
	javac RandomWalkers.java

SpecDay.class: SpecDay.java
	javac SpecDay.java
