all: AsciiArt.class RandomWalker.class SpecDay.class

AsciiArt.class: AsciiArt.java
	javac AsciiArt.java

RandomWalker.class: RandomWalker.java
	javac RandomWalker.java

SpecDay.class: SpecDay.java
	javac SpecDay.java
